user:
    pattern:  /
    defaults: { _controller: "netagoraBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "netagoraBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "netagoraBundle:User:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "netagoraBundle:User:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "netagoraBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "netagoraBundle:User:update" }
    requirements: { _method: post }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "netagoraBundle:User:delete" }
    requirements: { _method: post }
